version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: DockerfileNode
    container_name: app_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testnutech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump-test-nutech.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  backend:

volumes:
  postgres_data:
